name: manage-azure-policy-c118c8ce
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Apply_Diagnostic_Settings_for_Microsoft.Web/sites_(app,linux)_to_a_Log_Analytics_Workspace_a3d948d7-bd35-4f83-bac9-630e9eedfdb2/**'
#      - .github/workflows/manage-azure-policy-c118c8ce.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c118c8ce}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Apply_Diagnostic_Settings_for_Microsoft.Web/sites_(app,linux)_to_a_Log_Analytics_Workspace_a3d948d7-bd35-4f83-bac9-630e9eedfdb2/**
