name: manage-azure-policy-c7855d58
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'AMPLS/policies/_AMPLS_Custom_Configure_Ass_to_link_virtual_machines_to_user-defined_Microsoft_Defender_for_Cloud_Data_Collection_Rule_and_EP_64b25598-7d18-4870-be44-bbd8c3a2ed86/**'
#      - .github/workflows/manage-azure-policy-c7855d58.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c7855d58}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          AMPLS/policies/_AMPLS_Custom_Configure_Ass_to_link_virtual_machines_to_user-defined_Microsoft_Defender_for_Cloud_Data_Collection_Rule_and_EP_64b25598-7d18-4870-be44-bbd8c3a2ed86/**
