name: manage-azure-policy-29166c37
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Apply_Diagnostic_Settings_for_Microsoft.KeyVault/vaults_to_a_Log_Analytics_Workspace_c5da1921-89ff-4857-bf39-3d505b80cfa6/**'
#      - .github/workflows/manage-azure-policy-29166c37.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_29166c37}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Apply_Diagnostic_Settings_for_Microsoft.KeyVault/vaults_to_a_Log_Analytics_Workspace_c5da1921-89ff-4857-bf39-3d505b80cfa6/**
