name: manage-azure-policy-d222df6a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Apply_Diagnostic_Settings_for_Azure_VM_to_a_Log_Analytics_Workspace_apply-diagnostic-setting-azvm-loganalytics/**'
#      - .github/workflows/manage-azure-policy-d222df6a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d222df6a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Apply_Diagnostic_Settings_for_Azure_VM_to_a_Log_Analytics_Workspace_apply-diagnostic-setting-azvm-loganalytics/**
